#!/usr/bin/env bash
# The parameters for data generation. 100 million points roughly produces 36GB data size
NUM_OF_POINTS=2800000  #1g
NUM_OF_CLUSTERS=10
DIMENSIONS=20
SCALING=0.6
NUM_OF_PARTITIONS=10

MAX_ITERATION=5
NUM_RUN=1

SPARK_EXECUTOR_MEMORY="1250m"
STORAGE_LEVEL="MEMORY_AND_DISK_SER"
SPARK_STORAGE_MEMORYFRACTION=0.48
TYPE="1G"
EXEMEM="1024"
